"""??????????"""


from abc import ABC, abstractmethod
from typing import Dict, Any, List, Optional, Callable, get_type_hints
from pydantic import BaseModel
import inspect
import re


def tool_action(name: str = None, description: str = None):
    """
    負責執行 tools.base 中的 tool_action 流程，依照 tools.base 的流程需求處理 tool_action 對應的資料轉換、狀態操作或結果產生。
    
    Args:
        name: 此流程需要使用的輸入資料。
        description: 此流程需要使用的輸入資料。
    
    Returns:
        執行結果；若函式標註回傳型別，預期型別為 未標註。
    
    限制或副作用:
        可能讀取或更新物件狀態、檔案、外部服務或日誌；請依呼叫場景確認副作用。
    """
    def decorator(func: Callable):
        """
        負責執行 tools.base 中的 decorator 流程，依照 tools.base 的流程需求處理 decorator 對應的資料轉換、狀態操作或結果產生。
        
        Args:
            func: 此流程需要使用的輸入資料。
        
        Returns:
            執行結果；若函式標註回傳型別，預期型別為 未標註。
        
        限制或副作用:
            可能讀取或更新物件狀態、檔案、外部服務或日誌；請依呼叫場景確認副作用。
        """
        func._is_tool_action = True
        func._tool_name = name
        func._tool_description = description
        return func
    return decorator


class ToolParameter(BaseModel):
    """
    負責在 tools.base 中封裝 ToolParameter，封裝工具呼叫、參數處理與工具結果回傳流程。
    
    Args:
        無明確建構參數，可能透過 dataclass 欄位或預設值建立物件。
    
    Returns:
        類別本身不直接回傳值；建立實例後可透過其方法操作狀態與流程。
    
    限制或副作用:
        方法可能更新內部狀態、讀寫檔案、呼叫外部服務或產生日誌，需依使用情境確認。
    """
    name: str
    type: str
    description: str
    required: bool = True
    default: Any = None


class Tool(ABC):
    """
    負責在 tools.base 中封裝 Tool，封裝工具呼叫、參數處理與工具結果回傳流程。
    
    Args:
        name: 此流程需要使用的輸入資料。
        description: 此流程需要使用的輸入資料。
        expandable: 此流程需要使用的輸入資料。
    
    Returns:
        類別本身不直接回傳值；建立實例後可透過其方法操作狀態與流程。
    
    限制或副作用:
        方法可能更新內部狀態、讀寫檔案、呼叫外部服務或產生日誌，需依使用情境確認。
    """

    def __init__(self, name: str, description: str, expandable: bool = False):
        """
        負責執行 Tool 中的 __init__ 流程，初始化物件所需的設定、依賴與內部狀態，讓後續方法可以沿用同一份執行上下文。
        
        Args:
            name: 此流程需要使用的輸入資料。
            description: 此流程需要使用的輸入資料。
            expandable: 此流程需要使用的輸入資料。
        
        Returns:
            執行結果；若函式標註回傳型別，預期型別為 未標註。
        
        限制或副作用:
            可能讀取或更新物件狀態、檔案、外部服務或日誌；請依呼叫場景確認副作用。
        """
        self.name = name
        self.description = description
        self.expandable = expandable

    @abstractmethod
    def run(self, parameters: Dict[str, Any]) -> str:
        """
        負責執行 Tool 中的 run 流程，啟動主要執行流程，串接輸入準備、核心處理與結果輸出。
        
        Args:
            parameters: 此流程需要使用的輸入資料。
        
        Returns:
            執行結果；若函式標註回傳型別，預期型別為 str。
        
        限制或副作用:
            可能讀取或更新物件狀態、檔案、外部服務或日誌；請依呼叫場景確認副作用。
        """
        pass

    @abstractmethod
    def get_parameters(self) -> List[ToolParameter]:
        """
        負責執行 Tool 中的 get_parameters 流程，依照 Tool 的流程需求處理 get_parameters 對應的資料轉換、狀態操作或結果產生。
        
        Args:
            無。
        
        Returns:
            執行結果；若函式標註回傳型別，預期型別為 List[ToolParameter]。
        
        限制或副作用:
            可能讀取或更新物件狀態、檔案、外部服務或日誌；請依呼叫場景確認副作用。
        """
        pass

    def get_expanded_tools(self) -> Optional[List['Tool']]:
        """
        負責執行 Tool 中的 get_expanded_tools 流程，依照 Tool 的流程需求處理 get_expanded_tools 對應的資料轉換、狀態操作或結果產生。
        
        Args:
            無。
        
        Returns:
            執行結果；若函式標註回傳型別，預期型別為 Optional[List['Tool']]。
        
        限制或副作用:
            可能讀取或更新物件狀態、檔案、外部服務或日誌；請依呼叫場景確認副作用。
        """
        if not self.expandable:
            return None

        # 自動從裝飾器標記的方法生成工具
        tools = []
        for name, method in inspect.getmembers(self, predicate=inspect.ismethod):
            if hasattr(method, '_is_tool_action'):
                tool = AutoGeneratedTool(
                    parent=self,
                    method=method,
                    name=method._tool_name,
                    description=method._tool_description
                )
                tools.append(tool)

        return tools if tools else None

    def validate_parameters(self, parameters: Dict[str, Any]) -> bool:
        """
        負責執行 Tool 中的 validate_parameters 流程，檢查目前輸入、狀態或條件是否符合流程繼續執行的要求。
        
        Args:
            parameters: 此流程需要使用的輸入資料。
        
        Returns:
            執行結果；若函式標註回傳型別，預期型別為 bool。
        
        限制或副作用:
            可能讀取或更新物件狀態、檔案、外部服務或日誌；請依呼叫場景確認副作用。
        """
        required_params = [p.name for p in self.get_parameters() if p.required]
        return all(param in parameters for param in required_params)

    def to_dict(self) -> Dict[str, Any]:
        """
        負責執行 Tool 中的 to_dict 流程，將內部資料整理成日誌、提示詞、摘要或指定的輸出格式。
        
        Args:
            無。
        
        Returns:
            執行結果；若函式標註回傳型別，預期型別為 Dict[str, Any]。
        
        限制或副作用:
            可能讀取或更新物件狀態、檔案、外部服務或日誌；請依呼叫場景確認副作用。
        """
        return {
            "name": self.name,
            "description": self.description,
            "parameters": [param.dict() for param in self.get_parameters()]
        }

    def to_openai_schema(self) -> Dict[str, Any]:
        """
        負責執行 Tool 中的 to_openai_schema 流程，將內部資料整理成日誌、提示詞、摘要或指定的輸出格式。
        
        Args:
            無。
        
        Returns:
            執行結果；若函式標註回傳型別，預期型別為 Dict[str, Any]。
        
        限制或副作用:
            可能讀取或更新物件狀態、檔案、外部服務或日誌；請依呼叫場景確認副作用。
        """
        parameters = self.get_parameters()

        # 建構 properties
        properties = {}
        required = []

        for param in parameters:
            # 基礎屬性定義
            prop = {
                "type": param.type,
                "description": param.description
            }

            # 如果有預設值，添加到描述中（OpenAI schema 不支援 default 字段）
            if param.default is not None:
                prop["description"] = f"{param.description} (預設: {param.default})"

            # 如果是數組類型，添加 items 定義
            if param.type == "array":
                prop["items"] = {"type": "string"}  # 預設字串數組

            properties[param.name] = prop

            # 收集必需參數
            if param.required:
                required.append(param.name)

        return {
            "type": "function",
            "function": {
                "name": self.name,
                "description": self.description,
                "parameters": {
                    "type": "object",
                    "properties": properties,
                    "required": required
                }
            }
        }

    def __str__(self) -> str:
        """
        負責執行 Tool 中的 __str__ 流程，依照 Tool 的流程需求處理 __str__ 對應的資料轉換、狀態操作或結果產生。
        
        Args:
            無。
        
        Returns:
            執行結果；若函式標註回傳型別，預期型別為 str。
        
        限制或副作用:
            可能讀取或更新物件狀態、檔案、外部服務或日誌；請依呼叫場景確認副作用。
        """
        return f"Tool(name={self.name})"

    def __repr__(self) -> str:
        """
        負責執行 Tool 中的 __repr__ 流程，依照 Tool 的流程需求處理 __repr__ 對應的資料轉換、狀態操作或結果產生。
        
        Args:
            無。
        
        Returns:
            執行結果；若函式標註回傳型別，預期型別為 str。
        
        限制或副作用:
            可能讀取或更新物件狀態、檔案、外部服務或日誌；請依呼叫場景確認副作用。
        """
        return self.__str__()


class AutoGeneratedTool(Tool):
    """
    負責在 tools.base 中封裝 AutoGeneratedTool，封裝工具呼叫、參數處理與工具結果回傳流程。
    
    Args:
        parent: 此流程需要使用的輸入資料。
        method: 此流程需要使用的輸入資料。
        name: 此流程需要使用的輸入資料。
        description: 此流程需要使用的輸入資料。
    
    Returns:
        類別本身不直接回傳值；建立實例後可透過其方法操作狀態與流程。
    
    限制或副作用:
        方法可能更新內部狀態、讀寫檔案、呼叫外部服務或產生日誌，需依使用情境確認。
    """

    def __init__(self, parent: Tool, method: Callable, name: str = None, description: str = None):
        """
        負責執行 AutoGeneratedTool 中的 __init__ 流程，初始化物件所需的設定、依賴與內部狀態，讓後續方法可以沿用同一份執行上下文。
        
        Args:
            parent: 此流程需要使用的輸入資料。
            method: 此流程需要使用的輸入資料。
            name: 此流程需要使用的輸入資料。
            description: 此流程需要使用的輸入資料。
        
        Returns:
            執行結果；若函式標註回傳型別，預期型別為 未標註。
        
        限制或副作用:
            可能讀取或更新物件狀態、檔案、外部服務或日誌；請依呼叫場景確認副作用。
        """
        self.parent = parent
        self.method = method

        # 生成工具名稱
        if name is None:
            # 從方法名生成：_add_memory -> parent_name_add_memory
            method_name = method.__name__.lstrip('_')
            name = f"{parent.name}_{method_name}"

        # 提取描述
        if description is None:
            description = self._extract_description_from_docstring()

        super().__init__(name=name, description=description)

        # 自動解析參數
        self._parameters = self._parse_parameters()

    def _extract_description_from_docstring(self) -> str:
        """
        負責執行 AutoGeneratedTool 中的 _extract_description_from_docstring 流程，依照 AutoGeneratedTool 的流程需求處理 _extract_description_from_docstring 對應的資料轉換、狀態操作或結果產生。
        
        Args:
            無。
        
        Returns:
            執行結果；若函式標註回傳型別，預期型別為 str。
        
        限制或副作用:
            可能讀取或更新物件狀態、檔案、外部服務或日誌；請依呼叫場景確認副作用。
        """
        doc = inspect.getdoc(self.method)
        if not doc:
            return f"執行 {self.method.__name__}"

        # 提取第一行作為描述
        lines = doc.split('\n')
        for line in lines:
            line = line.strip()
            if line and not line.startswith('Args:') and not line.startswith('Returns:'):
                return line

        return f"執行 {self.method.__name__}"

    def _parse_parameters(self) -> List[ToolParameter]:
        """
        負責執行 AutoGeneratedTool 中的 _parse_parameters 流程，依照 AutoGeneratedTool 的流程需求處理 _parse_parameters 對應的資料轉換、狀態操作或結果產生。
        
        Args:
            無。
        
        Returns:
            執行結果；若函式標註回傳型別，預期型別為 List[ToolParameter]。
        
        限制或副作用:
            可能讀取或更新物件狀態、檔案、外部服務或日誌；請依呼叫場景確認副作用。
        """
        sig = inspect.signature(self.method)
        type_hints = get_type_hints(self.method)
        docstring = inspect.getdoc(self.method) or ""

        # 從 docstring 解析參數描述
        param_descriptions = self._parse_param_descriptions(docstring)

        parameters = []
        for param_name, param in sig.parameters.items():
            if param_name == 'self':
                continue

            # 取得類型
            param_type_hint = type_hints.get(param_name, str)
            param_type = self._python_type_to_tool_type(param_type_hint)

            # 判斷是否必需
            required = param.default == inspect.Parameter.empty
            default = None if required else param.default

            # 取得描述
            description = param_descriptions.get(param_name, f"參數 {param_name}")

            parameters.append(ToolParameter(
                name=param_name,
                type=param_type,
                description=description,
                required=required,
                default=default
            ))

        return parameters

    def _parse_param_descriptions(self, docstring: str) -> Dict[str, str]:
        """
        負責執行 AutoGeneratedTool 中的 _parse_param_descriptions 流程，依照 AutoGeneratedTool 的流程需求處理 _parse_param_descriptions 對應的資料轉換、狀態操作或結果產生。
        
        Args:
            docstring: 此流程需要使用的輸入資料。
        
        Returns:
            執行結果；若函式標註回傳型別，預期型別為 Dict[str, str]。
        
        限制或副作用:
            可能讀取或更新物件狀態、檔案、外部服務或日誌；請依呼叫場景確認副作用。
        """
        descriptions = {}

        # 查找 Args: 部分
        args_match = re.search(r'Args:\s*\n(.*?)(?:\n\s*\n|Returns:|$)', docstring, re.DOTALL)
        if not args_match:
            return descriptions

        args_section = args_match.group(1)

        # 解析每個參數
        # 匹配格式: param_name: 描述 或 param_name (type): 描述
        param_pattern = r'^\s*(\w+)(?:\s*\([^)]+\))?\s*:\s*(.+?)(?=^\s*\w+\s*(?:\([^)]+\))?\s*:|$)'
        matches = re.finditer(param_pattern, args_section, re.MULTILINE | re.DOTALL)

        for match in matches:
            param_name = match.group(1).strip()
            param_desc = match.group(2).strip()
            # 清理描述中的多余空白
            param_desc = re.sub(r'\s+', ' ', param_desc)
            descriptions[param_name] = param_desc

        return descriptions

    def _python_type_to_tool_type(self, py_type) -> str:
        """
        負責執行 AutoGeneratedTool 中的 _python_type_to_tool_type 流程，依照 AutoGeneratedTool 的流程需求處理 _python_type_to_tool_type 對應的資料轉換、狀態操作或結果產生。
        
        Args:
            py_type: 此流程需要使用的輸入資料。
        
        Returns:
            執行結果；若函式標註回傳型別，預期型別為 str。
        
        限制或副作用:
            可能讀取或更新物件狀態、檔案、外部服務或日誌；請依呼叫場景確認副作用。
        """
        # 處理泛型類型
        origin = getattr(py_type, '__origin__', None)
        if origin is not None:
            if origin is list:
                return "array"
            elif origin is dict:
                return "object"

        # 處理基本類型
        type_map = {
            str: "string",
            int: "integer",
            float: "number",
            bool: "boolean",
            list: "array",
            dict: "object",
        }

        return type_map.get(py_type, "string")

    def get_parameters(self) -> List[ToolParameter]:
        """
        負責執行 AutoGeneratedTool 中的 get_parameters 流程，依照 AutoGeneratedTool 的流程需求處理 get_parameters 對應的資料轉換、狀態操作或結果產生。
        
        Args:
            無。
        
        Returns:
            執行結果；若函式標註回傳型別，預期型別為 List[ToolParameter]。
        
        限制或副作用:
            可能讀取或更新物件狀態、檔案、外部服務或日誌；請依呼叫場景確認副作用。
        """
        return self._parameters

    def run(self, parameters: Dict[str, Any]) -> str:
        """
        負責執行 AutoGeneratedTool 中的 run 流程，啟動主要執行流程，串接輸入準備、核心處理與結果輸出。
        
        Args:
            parameters: 此流程需要使用的輸入資料。
        
        Returns:
            執行結果；若函式標註回傳型別，預期型別為 str。
        
        限制或副作用:
            可能讀取或更新物件狀態、檔案、外部服務或日誌；請依呼叫場景確認副作用。
        """
        return self.method(**parameters)
