"""??????????"""


from abc import ABC, abstractmethod
from typing import Dict, Any, List, Optional, Callable, get_type_hints
from pydantic import BaseModel
import inspect
import re


def tool_action(name: str = None, description: str = None):
    """裝飾器：標記一個方法為可展開的工具 action

    使用方式:
        @tool_action("memory_add", "添加新記憶")
        def _add_memory(self, content: str, importance: float = 0.5) -> str:
            '''添加記憶

            Args:
                content: 記憶內容
                importance: 重要性分數
            '''
            ...

    Args:
        name: 工具名稱（如果不提供，從方法名自動生成）
        description: 工具描述（如果不提供，從 docstring 提取）
    """
    def decorator(func: Callable):
        func._is_tool_action = True
        func._tool_name = name
        func._tool_description = description
        return func
    return decorator


class ToolParameter(BaseModel):
    """工具參數定義"""
    name: str
    type: str
    description: str
    required: bool = True
    default: Any = None


class Tool(ABC):
    """工具基類

    支援兩種使用模式：
    1. 普通模式：工具作為單一實體使用
    2. 可展開模式：工具可以展開為多個獨立的子工具（每個子工具對應一個功能）

    展開模式支援兩種實現方式：
    - 手動定義子工具類（傳統方式）
    - 使用 @tool_action 裝飾器自動生成（推薦）
    """

    def __init__(self, name: str, description: str, expandable: bool = False):
        """初始化工具

        Args:
            name: 工具名稱
            description: 工具描述
            expandable: 是否可展開為多個子工具
        """
        self.name = name
        self.description = description
        self.expandable = expandable

    @abstractmethod
    def run(self, parameters: Dict[str, Any]) -> str:
        """執行工具"""
        pass

    @abstractmethod
    def get_parameters(self) -> List[ToolParameter]:
        """取得工具參數定義"""
        pass

    def get_expanded_tools(self) -> Optional[List['Tool']]:
        """取得展開後的子工具列表

        預設實現：自動從標記了 @tool_action 的方法生成子工具
        子類可以重寫此方法提供自定義的展開邏輯

        Returns:
            如果工具支援展開，回傳子工具列表；否則回傳 None
        """
        if not self.expandable:
            return None

        # 自動從裝飾器標記的方法生成工具
        tools = []
        for name, method in inspect.getmembers(self, predicate=inspect.ismethod):
            if hasattr(method, '_is_tool_action'):
                tool = AutoGeneratedTool(
                    parent=self,
                    method=method,
                    name=method._tool_name,
                    description=method._tool_description
                )
                tools.append(tool)

        return tools if tools else None

    def validate_parameters(self, parameters: Dict[str, Any]) -> bool:
        """驗證參數"""
        required_params = [p.name for p in self.get_parameters() if p.required]
        return all(param in parameters for param in required_params)

    def to_dict(self) -> Dict[str, Any]:
        """轉換為字典格式"""
        return {
            "name": self.name,
            "description": self.description,
            "parameters": [param.dict() for param in self.get_parameters()]
        }

    def to_openai_schema(self) -> Dict[str, Any]:
        """轉換為 OpenAI function calling schema 格式

        用於 FunctionCallAgent，使工具能夠被 OpenAI 原生 function calling 使用

        Returns:
            符合 OpenAI function calling 標準的 schema
        """
        parameters = self.get_parameters()

        # 建構 properties
        properties = {}
        required = []

        for param in parameters:
            # 基礎屬性定義
            prop = {
                "type": param.type,
                "description": param.description
            }

            # 如果有預設值，添加到描述中（OpenAI schema 不支援 default 字段）
            if param.default is not None:
                prop["description"] = f"{param.description} (預設: {param.default})"

            # 如果是數組類型，添加 items 定義
            if param.type == "array":
                prop["items"] = {"type": "string"}  # 預設字串數組

            properties[param.name] = prop

            # 收集必需參數
            if param.required:
                required.append(param.name)

        return {
            "type": "function",
            "function": {
                "name": self.name,
                "description": self.description,
                "parameters": {
                    "type": "object",
                    "properties": properties,
                    "required": required
                }
            }
        }

    def __str__(self) -> str:
        return f"Tool(name={self.name})"

    def __repr__(self) -> str:
        return self.__str__()


class AutoGeneratedTool(Tool):
    """自動生成的工具 - 從方法簽名和 docstring 自動提取參數"""

    def __init__(self, parent: Tool, method: Callable, name: str = None, description: str = None):
        """初始化自動生成的工具

        Args:
            parent: 父工具實例
            method: 被裝飾的方法
            name: 工具名稱（如果為 None，從方法名生成）
            description: 工具描述（如果為 None，從 docstring 提取）
        """
        self.parent = parent
        self.method = method

        # 生成工具名稱
        if name is None:
            # 從方法名生成：_add_memory -> parent_name_add_memory
            method_name = method.__name__.lstrip('_')
            name = f"{parent.name}_{method_name}"

        # 提取描述
        if description is None:
            description = self._extract_description_from_docstring()

        super().__init__(name=name, description=description)

        # 自動解析參數
        self._parameters = self._parse_parameters()

    def _extract_description_from_docstring(self) -> str:
        """從 docstring 提取描述"""
        doc = inspect.getdoc(self.method)
        if not doc:
            return f"執行 {self.method.__name__}"

        # 提取第一行作為描述
        lines = doc.split('\n')
        for line in lines:
            line = line.strip()
            if line and not line.startswith('Args:') and not line.startswith('Returns:'):
                return line

        return f"執行 {self.method.__name__}"

    def _parse_parameters(self) -> List[ToolParameter]:
        """從方法簽名和 docstring 自動提取參數"""
        sig = inspect.signature(self.method)
        type_hints = get_type_hints(self.method)
        docstring = inspect.getdoc(self.method) or ""

        # 從 docstring 解析參數描述
        param_descriptions = self._parse_param_descriptions(docstring)

        parameters = []
        for param_name, param in sig.parameters.items():
            if param_name == 'self':
                continue

            # 取得類型
            param_type_hint = type_hints.get(param_name, str)
            param_type = self._python_type_to_tool_type(param_type_hint)

            # 判斷是否必需
            required = param.default == inspect.Parameter.empty
            default = None if required else param.default

            # 取得描述
            description = param_descriptions.get(param_name, f"參數 {param_name}")

            parameters.append(ToolParameter(
                name=param_name,
                type=param_type,
                description=description,
                required=required,
                default=default
            ))

        return parameters

    def _parse_param_descriptions(self, docstring: str) -> Dict[str, str]:
        """從 docstring 解析參數描述

        支援格式:
            Args:
                param_name: 參數描述
                another_param: 另一個參數描述
        """
        descriptions = {}

        # 查找 Args: 部分
        args_match = re.search(r'Args:\s*\n(.*?)(?:\n\s*\n|Returns:|$)', docstring, re.DOTALL)
        if not args_match:
            return descriptions

        args_section = args_match.group(1)

        # 解析每個參數
        # 匹配格式: param_name: 描述 或 param_name (type): 描述
        param_pattern = r'^\s*(\w+)(?:\s*\([^)]+\))?\s*:\s*(.+?)(?=^\s*\w+\s*(?:\([^)]+\))?\s*:|$)'
        matches = re.finditer(param_pattern, args_section, re.MULTILINE | re.DOTALL)

        for match in matches:
            param_name = match.group(1).strip()
            param_desc = match.group(2).strip()
            # 清理描述中的多余空白
            param_desc = re.sub(r'\s+', ' ', param_desc)
            descriptions[param_name] = param_desc

        return descriptions

    def _python_type_to_tool_type(self, py_type) -> str:
        """將 Python 類型轉換為工具類型字串"""
        # 處理泛型類型
        origin = getattr(py_type, '__origin__', None)
        if origin is not None:
            if origin is list:
                return "array"
            elif origin is dict:
                return "object"

        # 處理基本類型
        type_map = {
            str: "string",
            int: "integer",
            float: "number",
            bool: "boolean",
            list: "array",
            dict: "object",
        }

        return type_map.get(py_type, "string")

    def get_parameters(self) -> List[ToolParameter]:
        """取得參數列表"""
        return self._parameters

    def run(self, parameters: Dict[str, Any]) -> str:
        """執行方法"""
        return self.method(**parameters)
